Nice, looks like I broke pytorch.
bollu@gnode36:~/alok-bollu/word2blank/word2blank$ ./run.py train
--savepath experiment pseudoreimann
setting up device...
device: cuda:3
    Done. time: 0:00:00.994991
--
Creating new parameters...
    loading corpus: text8...
number of words in corpus (original): 17005207
        filtering stopwords...
            Done. time: 0:00:03.534838
--
        filtering low frequency words... (all frequencies that account
for < 20% of the dataset)...
filtered #2191564 (20.039166442568 percent) words. New corpus size:
8744839 (79.960833557432 percent of original)
            Done. time: 0:00:06.140917
--
taking N(10000) words form the corpus:
        Done. time: 0:00:13.085766
    building vocabulary...
        Done. time: 0:00:00.000626
    creating word2man...
        creating EMBEDM...
            Done. time: 0:00:02.673112
        creating METRIC...
            Done. time: 0:00:00.004053
        Done. time: 0:00:02.677581
    creating OPTIMISER...
        Done. time: 0:00:00.000210
    creating dataset......
        creating I2W, W2I...
            Done. time: 0:00:00.001050
        counting frequency of words...
            Done. time: 0:00:00.001436
        Done. time: 0:00:00.002561
    creating DATA
...
        Done. time: 0:00:00.000142
    Done. time: 0:00:15.911755
N/A% (0 of 7900) |
| Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
  File "./run.py", line 666, in <module>
    main()
  File "./run.py", line 659, in main
    traincli(PARSED.savepath)
  File "./run.py", line 623, in traincli
    l.backward()
  File "/home/bollu/.local/lib/python3.5/site-packages/torch/tensor.py",
line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File
"/home/bollu/.local/lib/python3.5/site-packages/torch/autograd/__init__.py",
line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: N <= iter.ntensors() ASSERT FAILED at
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:13, please report a
bug to PyTorch.